### ISSUE TITLE
Redesign ExtensionCard components

### ISSUE THREAD

**Issue by rainzee** [nonedesktop/Nonebot-Desktop-Qt#3]
Redesigning the ExtensionCard component, I think instead of splitting up the plugin cards and adapter cards, we should unify them into one ExtensionCard and use icons to distinguish the card types.

**Comment by NCBM** [comment]
IMO ExtensionCards need at least 3 icons for `adapter`, `plugin-application` and `plugin-library`. Another icon is needed if drivers would be included.

**Comment by rainzee** [comment]
Filter the available icons from here, remember the code of the icon, which I will extract from the font file and add to the ICON https://github.com/microsoft/fluentui-system-icons

**Comment by NCBM** [comment]
- `Apps` for `plugin-application`
- `Box Multiple` for `plugin-library`
- `Group` for `adapter`

These are my suggestions.

**Comment by rainzee** [comment]
@NCBM We've completed the main design work, now what else do you think needs to be done and let's plan it out.

**Comment by NCBM** [comment]
> @NCBM We've completed the main design work, now what else do you think needs to be done and let's plan it out.

@rainzee Actually we cannot even manage any instances for now, so imo we need to pay effort on a manage backend ([nonedesktop/nonefly](https://github.com/nonedesktop/nonefly), as the [wing lib](https://github.com/nonedesktop/nonebot-desktop-wing) is still confusing)

**Comment by rainzee** [comment]
Then I'll mark this phase of planned development closed, and you can open a new topic to plan the back-end development tasks and assign specific subtasks to me.
